import { notFound } from 'next/navigation';
import Link from 'next/link';
import SiteHeader from '../../site-header';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import type { Project, ProjectBlock } from '@/lib/projects';
import ProjectBlocks from '../project-blocks';

export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const db=await createServerSupabaseClient();const {data}=await db.from('threads').select('*').eq('destination','projects').eq('slug',slug).eq('status','published').maybeSingle();if(!data)notFound();const project=data as Project;const [{data:blocks},{data:logs}]=await Promise.all([db.from('project_blocks').select('*').eq('project_id',project.id).order('sort_order').order('created_at'),db.from('project_dev_logs').select('id,slug,title,entry_date,version,tag,summary').eq('project_id',project.id).eq('status','published').order('entry_date',{ascending:false}).limit(3)]);
  return <><SiteHeader revealImmediately activeHref="/projects"/><main className="project-page"><Link className="project-back" href="/projects">← ALL PROJECTS</Link><header className="project-header"><p>PROJECT / {project.category||'OTHER'}</p><h1>{project.title}</h1><dl><div><dt>STATUS</dt><dd>{project.status.toUpperCase()}</dd></div><div><dt>VERSION</dt><dd>{project.project_version??'—'}</dd></div><div><dt>DOMAIN</dt><dd>{project.category||'—'}</dd></div><div><dt>STARTED</dt><dd>{project.project_started_on??'—'}</dd></div><div><dt>UPDATED</dt><dd>{new Intl.DateTimeFormat('en-GB',{month:'short',year:'numeric'}).format(new Date(project.updated_at))}</dd></div><div><dt>STACK</dt><dd>{project.tags.join(' / ')||'—'}</dd></div>{project.project_progress!==null&&<div><dt>PROGRESS</dt><dd>{project.project_progress}%</dd></div>}{project.project_repository&&<div><dt>REPOSITORY</dt><dd><a href={`https://github.com/${project.project_repository}`} target="_blank" rel="noreferrer">GitHub ↗</a></dd></div>}</dl></header>{project.cover_media_reference&&<figure className="project-cover"><img src={project.cover_media_reference} alt="" style={{objectPosition:`${project.cover_position_x}% ${project.cover_position_y}%`}}/></figure>}<ProjectBlocks blocks={(blocks??[]) as ProjectBlock[]} repository={project.project_repository}/>{Boolean(logs?.length)&&<section className="project-devlog-preview"><header><small>DEVELOPMENT LOG</small><h2>Recent technical progress</h2></header>{logs?.map(log=><article key={log.id}><small>{log.entry_date}{log.version?` / ${log.version}`:''}{log.tag?` / ${log.tag}`:''}</small><h3>{log.title}</h3><p>{log.summary}</p><Link href={`/projects/${project.slug}/devlog/${log.slug}`}>READ LOG ↗</Link></article>)}<Link className="project-devlog-all" href={`/projects/${project.slug}/devlog`}>VIEW ALL DEV LOGS ↗</Link></section>}</main></>;
}
