"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
type Factor={id:string;friendly_name?:string;status:string;created_at:string};
export default function SecurityCenter(){const supabase=useMemo(()=>createBrowserSupabaseClient(),[]),router=useRouter();const [email,setEmail]=useState(""),[level,setLevel]=useState("—"),[factors,setFactors]=useState<Factor[]>([]),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[pending,setPending]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
const load=async()=>{const [{data:user},{data:list},{data:aal}]=await Promise.all([supabase.auth.getUser(),supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);setEmail(user.user?.email??"");setFactors((list?.totp??[]) as Factor[]);setLevel(aal?.currentLevel??"—")};useEffect(()=>{const timer=window.setTimeout(()=>{void Promise.all([supabase.auth.getUser(),supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]).then(([{data:user},{data:list},{data:aal}])=>{setEmail(user.user?.email??"");setFactors((list?.totp??[]) as Factor[]);setLevel(aal?.currentLevel??"—")})},0);return()=>window.clearTimeout(timer)},[supabase]);
const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");setNotice("");try{await action()}catch(reason){setError(reason instanceof Error?reason.message:"Security operation failed.")}finally{setBusy(false)}};
const password=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),current=String(data.get("current")),next=String(data.get("next")),confirm=String(data.get("confirm"));if(next.length<12||next!==confirm){setError("Use at least 12 characters and make both new passwords match.");return}await run(async()=>{const {error}=await supabase.auth.updateUser({password:next,current_password:current} as Parameters<typeof supabase.auth.updateUser>[0]);if(error)throw error;event.currentTarget.reset();setNotice("Password updated.")})};
const enroll=()=>run(async()=>{const {data,error}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:"Portfolio admin"});if(error)throw error;setPending(data.id);setQr(data.totp.qr_code);setSecret(data.totp.secret)});
const verify=()=>run(async()=>{const challenge=await supabase.auth.mfa.challenge({factorId:pending});if(challenge.error)throw challenge.error;const result=await supabase.auth.mfa.verify({factorId:pending,challengeId:challenge.data.id,code});if(result.error)throw result.error;setQr("");setSecret("");setPending("");setCode("");setNotice("Authenticator verified.");await load()});
const remove=(id:string)=>run(async()=>{if(factors.filter(f=>f.status==="verified").length<=1)throw new Error("The final verified factor cannot be removed because Admin requires MFA.");if(!confirm("Remove this authenticator factor?"))return;const {error}=await supabase.auth.mfa.unenroll({factorId:id});if(error)throw error;setNotice("Authenticator removed.");await load()});
const signOut=(scope:"local"|"others"|"global")=>run(async()=>{if(scope!=="local"&&!confirm(scope==="others"?"Sign out every other session?":"Sign out every session?"))return;const {error}=await supabase.auth.signOut({scope});if(error)throw error;if(scope!=="others"){router.push("/login");router.refresh()}else setNotice("Other sessions signed out.")});
return <div className="admin-security-center"><section><h3>ACCOUNT STATUS</h3><dl><div><dt>ADMIN EMAIL</dt><dd>{email||"—"}</dd></div><div><dt>ASSURANCE LEVEL</dt><dd>{level.toUpperCase()}</dd></div><div><dt>VERIFIED FACTORS</dt><dd>{factors.filter(item=>item.status==="verified").length}</dd></div></dl></section><section><h3>CHANGE PASSWORD</h3><form onSubmit={password}><label>Current password<input name="current" type="password" required autoComplete="current-password" /></label><label>New password<input name="next" type="password" required minLength={12} autoComplete="new-password" /></label><label>Confirm new password<input name="confirm" type="password" required minLength={12} autoComplete="new-password" /></label><button disabled={busy}>UPDATE PASSWORD</button></form></section><section><h3>TWO-FACTOR AUTHENTICATION</h3>{factors.map(factor=><article key={factor.id}><div><strong>{factor.friendly_name||"Authenticator"}</strong><small>{factor.status.toUpperCase()} / {new Date(factor.created_at).toLocaleDateString("en-GB")}</small></div><button type="button" disabled={busy||factors.filter(item=>item.status==="verified").length<=1} onClick={()=>void remove(factor.id)}>REMOVE</button></article>)}{!pending&&<button type="button" disabled={busy} onClick={()=>void enroll()}>+ ENROLL AUTHENTICATOR</button>}{pending&&<div className="security-enrollment"><img src={qr} alt="Authenticator QR code"/><p>Manual secret: <code>{secret}</code></p><label>Verification code<input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))}/></label><button type="button" disabled={busy||code.length!==6} onClick={()=>void verify()}>VERIFY FACTOR</button></div>}</section><section><h3>SESSION SECURITY</h3><div className="admin-security-actions"><button type="button" disabled={busy} onClick={()=>void signOut("local")}>SIGN OUT THIS SESSION</button><button type="button" disabled={busy} onClick={()=>void signOut("others")}>SIGN OUT OTHER SESSIONS</button><button type="button" disabled={busy} onClick={()=>void signOut("global")}>SIGN OUT ALL SESSIONS</button></div></section><p className="admin-profile-error" role="alert" aria-live="polite">{error}</p><p className="admin-profile-notice" role="status" aria-live="polite">{notice}</p></div>}
