'use client';

import Image from 'next/image';
import { FormEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createBrowserSupabaseClient } from '@/lib/supabase/browser';

type Enrollment = {
  factorId: string;
  qrCode: string;
  secret: string;
};

export default function AuthenticatorGate({ factorId }: { factorId: string | null }) {
  const router = useRouter();
  const supabase = useMemo(() => createBrowserSupabaseClient(), []);
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null);
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [isWorking, setIsWorking] = useState(false);

  const beginEnrollment = async () => {
    setError('');
    setIsWorking(true);

    try {
      // Remove abandoned setup attempts before issuing one fresh authenticator secret.
      const { data: factors, error: listError } = await supabase.auth.mfa.listFactors();
      if (listError) throw listError;

      const unfinishedFactors = factors.all.filter((factor) => factor.status === 'unverified');
      for (const factor of unfinishedFactors) {
        await supabase.auth.mfa.unenroll({ factorId: factor.id });
      }

      const { data, error: enrollError } = await supabase.auth.mfa.enroll({
        factorType: 'totp',
        friendlyName: 'Portfolio administrator',
      });
      if (enrollError) throw enrollError;

      setEnrollment({
        factorId: data.id,
        qrCode: data.totp.qr_code,
        secret: data.totp.secret,
      });
    } catch {
      setError('Authenticator setup could not start. Sign in again and retry.');
    } finally {
      setIsWorking(false);
    }
  };

  const verifyCode = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    const cleanCode = code.replace(/\s/g, '');
    const activeFactorId = factorId ?? enrollment?.factorId;

    if (!activeFactorId || !/^\d{6}$/.test(cleanCode)) {
      setError('Enter the six-digit code from your authenticator app.');
      return;
    }

    setIsWorking(true);

    try {
      const { data: challenge, error: challengeError } = await supabase.auth.mfa.challenge({
        factorId: activeFactorId,
      });
      if (challengeError) throw challengeError;

      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId: activeFactorId,
        challengeId: challenge.id,
        code: cleanCode,
      });
      if (verifyError) throw verifyError;

      router.replace('/admin');
      router.refresh();
    } catch {
      setError('That code was not accepted. Wait for a new code and try again.');
    } finally {
      setIsWorking(false);
    }
  };

  const isSetup = !factorId;

  return (
    <section className="security-panel" aria-labelledby="security-title">
      <div className="security-index" aria-hidden="true">
        <span>SEC / 02</span>
        <strong>{isSetup ? 'ENROL' : 'VERIFY'}</strong>
        <i />
      </div>

      <div className="security-content">
        <div className="security-heading">
          <span>{isSetup ? 'New security factor' : 'Identity confirmation'}</span>
          <span>AUTHENTICATOR</span>
        </div>
        <h1 id="security-title">
          {isSetup ? 'Secure this account.' : 'Enter your code.'}
        </h1>

        {isSetup && !enrollment && (
          <>
            <p className="security-description">
              Connect Google Authenticator, Microsoft Authenticator, 1Password, or another TOTP app.
            </p>
            <button className="security-primary" type="button" onClick={beginEnrollment} disabled={isWorking}>
              <span>{isWorking ? 'Preparing…' : 'Create secure QR code'}</span>
              <span aria-hidden="true">→</span>
            </button>
          </>
        )}

        {isSetup && enrollment && (
          <div className="security-enrollment">
            <div className="security-qr">
              <Image src={enrollment.qrCode} alt="Authenticator setup QR code" width={220} height={220} unoptimized />
            </div>
            <div>
              <p>Scan the QR code, then enter the six-digit code generated by the app.</p>
              <span>Manual setup key</span>
              <code>{enrollment.secret}</code>
            </div>
          </div>
        )}

        {(!isSetup || enrollment) && (
          <form className="security-code-form" onSubmit={verifyCode}>
            <label htmlFor="authenticator-code">Six-digit code</label>
            <div className="security-code-shell">
              <span aria-hidden="true">03</span>
              <input
                id="authenticator-code"
                value={code}
                onChange={(event) => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))}
                type="text"
                inputMode="numeric"
                autoComplete="one-time-code"
                pattern="[0-9]{6}"
                maxLength={6}
                autoFocus
                required
              />
            </div>
            <button className="security-primary" type="submit" disabled={isWorking}>
              <span>{isWorking ? 'Verifying…' : isSetup ? 'Enable authenticator' : 'Unlock control surface'}</span>
              <span aria-hidden="true">→</span>
            </button>
          </form>
        )}

        <p className="security-error" role="alert" aria-live="polite">{error}</p>

        <form className="security-signout" action="/api/auth/logout" method="post">
          <button type="submit">Cancel and sign out</button>
        </form>
      </div>
    </section>
  );
}
